### ISSUE TITLE
Choose a single desktop to assign new wallpaper

### ISSUE THREAD

**Issue by joshnh** [adamdehaven/Wallpapers-from-Unsplash#3]
When working with multiple desktops it would be good to individually update wallpapers.

**Comment by adamdehaven** [comment]
@joshnh Have you tried the `monitor` command? It allows you to only update a single desktop

**Terminal Example**
`unsplash monitor 2`

**Alfred Workflow Example**
`monitor 2`

**Comment by joshnh** [comment]
I'm using OS X "desktop" terminology in that I'm only using my MacBook (no external display). Is that what you're also talking about?

**Comment by adamdehaven** [comment]
Yep, that command should update the image on the desktop number you specify. 

Give it a try and let me know if that's what you're wanting? Otherwise, maybe explain? 

If this is the intended behavior you're wanting, now I'm wondering if I should change the keyword from `monitor` to `desktop` ...?

**Comment by joshnh** [comment]
That is the behaviour I'm after. I didn't try monitor based on the wording.

**Comment by adamdehaven** [comment]
@joshnh: That's a good observation. I have changed the command from `monitor` to `desktop`. If you want the updated keywords, simply download the latest release.
